server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        - id: payment_routh
          #uri: http://localhost:8001
          uri: lb://cloud-payment-service # lb：loadbalance -> 在cloud-payment-service找的服务进行负载均衡
          predicates:
            - Path=/payment/get/**
        - id: payment_routh2
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/lb/**
            - After=2020-10-27T13:03:34.901+01:00[Europe/Berlin]
            # 提前上线，但是这个时间以后才实现
            # ZonedDateTime zbj = ZonedDateTime.now();
            - Cookie=username,zzyy
            - Header=X-Request-Id, \d+ # 请求头要有X-Request-Id 属性并且值为整数的正则表达式
            - Host=**.atguigu.com
            - Method=GET
            - Query=username, \d+ # 要有参数名username并且值还要是整数才行
            # curl http://localhost:9527/payment/lb\?username\=31 --cookie "username=zzyy" -H "X-Request-Id:1234" -H "Host:www.atguigu.com"
          filters:
            - AddRequestParameter=X-Request-Id,1024 # 过滤器工厂会在匹配的请求头加上一对请求头，名称为X-Request-Id值为1024

      discovery:
        locator:
          enabled: true

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    # false表示不向注册中心注册自己
    register-with-eureka: true
    # 是否从eurekaServer中抓取己有的注册信息，默认为true, 单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    # 注意这里是service 而不是 server
    service-url:
      # defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/ #集群版
      # 设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址
      # ${eureka.instance.hostname}: localhost
      # ${server.port}: eureka的访问地址
      defaultZone: http://eureka7001.com:7001/eureka/